[toolchain]
package_manager = "yarn"

[features]
resolution = false
skip-lint = false

[programs.localnet]
program-b = "FBgf9LtNm1bSvU92Bkwk3afCVn3nqZcy2gNVPKSpU9C4"
program_a = "HPB6ncb52NoeDCCAuyjDjd52ktYugHhfKxSPUqzfEqNg"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
